### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by glitchyordis** [rail-berkeley/hil-serl#10]
1. The [videos](https://hil-serl.github.io/) show that the robot inserts the USB and SSD into a specific slot. Do we need to train for slots located at different positions?
2. There is a mention of using impedance-based controller for Franka. Is it still possible to implement hil-serl on UR5e cobot because I think impedance control is unavailable for Universal Robots.

**Comment by jianlanluo** [comment]
1. No you’ll just need to use relative coordinates as in the appendix
2.you’ll need either impedance control or admittance control at high rate
for contact rich manipulation, you cant use position control for contact

**Comment by glitchyordis** [comment]
Is a significant change required if we use admittance control for HIL-SERL? I'm a beginner, so any pointers are appreciated.

**Comment by jianlanluo** [comment]
We haven't tried working with a UR nor an admittance controller for contact-rich manipulation. 

The other group from ETH successfully did this, see this PR: https://github.com/rail-berkeley/serl/pull/77 maybe you can contact them for more help
