### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by pumfish** [rail-berkeley/hil-serl#11]
Hello, I am adding new simulation environment experiments based on hil-serl. During the process of modifying the code, I noticed that there are some small issues in hil-serl. I have listed the problems I encountered regarding the source code below. 
I am not sure if I missed something that caused these codes to throw errors during my execution. I do not have a robotic arm, so I cannot reproduce the experiments provided in the source code.

1. Aren't the ```observations``` of env accessed first through ```images```, and then through specific pixels?
https://github.com/rail-berkeley/hil-serl/blob/433852ab0c237c21af90f3af3c0d29630f9756bd/serl_launcher/serl_launcher/data/memory_efficient_replay_buffer.py#L71C1-L73C87
2. I couldn't find the definition of ```monopi```. Does it refer to ```serl_launcher``` here?
https://github.com/rail-berkeley/hil-serl/blob/433852ab0c237c21af90f3af3c0d29630f9756bd/serl_launcher/serl_launcher/networks/actor_critic_nets.py#L10C1-L12C54
3. Is ```reward_classifier.py``` missing the imports for ```os```, ```requests```, and ```tqdm```?
https://github.com/rail-berkeley/hil-serl/blob/433852ab0c237c21af90f3af3c0d29630f9756bd/serl_launcher/serl_launcher/networks/reward_classifier.py#L89C1-L100C67

I have temporarily modified these areas to facilitate debugging my code. I noticed that the release date of the ```hil-serl``` code is not very long ago. I would greatly appreciate it if you could provide a stable version without errors.

**Comment by charlesxu0124** [comment]
Hi there,

1. The observation is flattened to `state` and `camera_name` by this observation wrapper in each experiments config file. [https://github.com/rail-berkeley/hil-serl/blob/4685b85b39244d74f4048948cee31a6520d5eac9/serl_launcher/serl_launcher/wrappers/serl_obs_wrappers.py#L5](https://github.com/rail-berkeley/hil-serl/blob/4685b85b39244d74f4048948cee31a6520d5eac9/serl_launcher/serl_launcher/wrappers/serl_obs_wrappers.py#L5)
2, 3. I've fixed the imports.
