### ISSUE TITLE
Run HIL-SERL in simulation without real-world robot

### ISSUE THREAD

**Issue by hexiao5886** [rail-berkeley/hil-serl#12]
I really want to try running the algorithm and experience the process of "teaching" robots, but I don't have a physical device.... So I would like to inquire if the existing code supports interaction within a simulation environment? If not, could you give me some advice on how I might need to modify the code to achieve this?

**Comment by jianlanluo** [comment]
try this one: https://github.com/rail-berkeley/serl/blob/main/docs/sim_quick_start.md
