### ISSUE TITLE
Is the target position fixed during the training process for the RAM-Insertion task?

### ISSUE THREAD

**Issue by pumfish** [rail-berkeley/hil-serl#2]
Hello, I’m studying the HIL-SERL code recently, and I came across the explanation of the ```RAM-Insertion``` task in ```franka_walkthrough.md```, where ```TARGET_POSE``` and ```GRASP_POSE``` are mentioned.
I see the ```TARGET_POSE``` and ```GRASP_POSE``` are set fixed value in the ```config.py```. My understanding is that during the training process, ```TARGET_POSE``` and ```GRASP_POSE``` remain fixed each time, but the initial position is random. Is this correct?
https://github.com/rail-berkeley/hil-serl/blob/2c63a3e027e488c025621376b9dda58cd3baaa9d/examples/experiments/ram_insertion/config.py#L39C1-L40C101

**Comment by jianlanluo** [comment]
Yes, if you use relative coordinate, this simulates the target moving, see the appendix in the paper for a discussion of this
