### ISSUE TITLE
How to control a robotiq hand-E gripper besides franka_hand and robotiq_2f?

### ISSUE THREAD

**Issue by ManUtdMoon** [rail-berkeley/hil-serl#4]
Dear authors,

Thank you for your efforts in creating and sharing this excellent project!

I noticed that a robotiq hand-E gripper is applied in this work, but the corresponding controller for it is not included in [serl_robot_infra](https://github.com/rail-berkeley/hil-serl/tree/main/serl_robot_infra) (I can only find franka_hand and robotiq_2f). Would you please recommend some choices about implementing the hand-E controller or will you release it in the future? Can I just reproduce it based on [robotiq_gripper_server.py](https://github.com/rail-berkeley/serl/blob/main/serl_robot_infra/robot_servers/robotiq_gripper_server.py)?

Thank you very much for your time and help!

Regards,
Dongjie

**Comment by jianlanluo** [comment]
yes you can modify the gripper server, shouldn't be hard
