### ISSUE TITLE
Synchronization Issue

### ISSUE THREAD

**Issue by BrunoFANG1** [rail-berkeley/hil-serl#8]
My experiment ran with ALOHA-like bi-arm robot instead of Franka robot. A major issue comes from this is the timestamp mismatch between the image and the pos. This has caused a negative effect on the real-world performance. Might worth a check before you do any experiments if you are not using the same hardware settings.

**Comment by jianlanluo** [comment]
Won't fix

the code doesn't do synchronization between images and proprios, in our franka experiments, it's in the order of 10ms, and it worked for us fine.

To this specific problem, this user had an unusual communication setup which caused the delay, it won't be a  general issue
