### ISSUE TITLE
Missing definition for 'value' in model_def.

### ISSUE THREAD

**Issue by pumfish** [rail-berkeley/hil-serl#9]
Hello, I am trying to apply Hil-serl to a new simulation environment for experimentation. 
I encountered the following issue when running the ```run_actor.sh```: 
```
File "xxx/Work/hil-serl/serl_launcher/serl_launcher/common/common.py", line 64, in __call__
    raise ValueError(
ValueError: When `name` is not specified, kwargs must contain the arguments for each module. Got kwargs keys dict_keys(['actor', 'critic', 'va
lue', 'temperature']) but module keys frozen_dict_keys(['actor', 'critic', 'temperature'])
I1125 19:49:12.820545 139818636830528 baseplatform.py:392] Platform import failed (likely during shutdown)
I1125 19:49:12.820688 139818636830528 baseplatform.py:392] Platform import failed (likely during shutdown)
I1125 19:49:12.820733 139818636830528 baseplatform.py:392] Platform import failed (likely during shutdown)
```
Upon inspecting the code, 
https://github.com/rail-berkeley/hil-serl/blob/433852ab0c237c21af90f3af3c0d29630f9756bd/serl_launcher/serl_launcher/agents/continuous/sac.py#L380C1-L401C20
I noticed that the ```network``` only has definitions for ```actor, critic, and temperature```, but ```value``` is added during initialization, leading to the error. I couldn't find where ```value``` is initialized in the Module. Did I miss something somewhere?

**Comment by jeffreywu13579** [comment]
Can you check if you have pulled the latest code?

**Comment by pumfish** [comment]
Sorry, I didn't realize that the repository's code has been updated. I noticed that the latest code no longer has the `value`. I will pull the latest code and try again. Thank you very much for your response.
